$path = 'c:\Users\ruchi\OneDrive\Documents\GitHub\My-Web-Revamp\experience.html';
$content = Get-Content $path;
$start = -1;
$end = -1;

for ($i=0; $i -lt $content.Length; $i++) {
    if ($content[$i] -match 'data-pc          const nodes') {
        $start = $i;
        break;
    }
}

if ($start -ne -1) {
    for ($i=$start; $i -lt $content.Length; $i++) {
        if ($content[$i] -match 'animate\(\);') {
            for ($j=$i; $j -lt $content.Length; $j++) {
                if ($content[$j] -match '</script>') {
                    $end = $j;
                    break;
                }
            }
            if ($end -ne -1) { break; }
        }
    }
}

if ($start -eq -1 -or $end -eq -1) {
    Write-Host "Failed to find anchors. Start: $start, End: $end";
    exit 1;
}

$newNodesAndScript = @(
'        <!-- 1: Game Dev -->',
'        <div class="nebula-node-wrap theme-dev" data-pct="95" data-x="20" data-y="25">',
'          <div class="nebula-node">',
'            <div class="nebula-cloud"></div>',
'            <div class="nebula-ring"></div>',
'            <div class="nebula-core"><svg viewBox="0 0 24 24">',
'                <rect x="6" y="3" width="12" height="15" rx="2" />',
'                <path d="M9 21h6v-3H9v3z" />',
'                <circle cx="12" cy="10" r="2" />',
'              </svg></div>',
'            <div class="nebula-label">Game Development</div>',
'          </div>',
'        </div>',
'',
'        <!-- 2: Vibe Coding -->',
'        <div class="nebula-node-wrap theme-dev" data-pct="98" data-x="75" data-y="20">',
'          <div class="nebula-node">',
'            <div class="nebula-cloud"></div>',
'            <div class="nebula-ring"></div>',
'            <div class="nebula-core"><svg viewBox="0 0 24 24">',
'                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87L18.18 22 12 18.27 5.82 22 7 14.14l-5-4.87 6.91-1.01L12 2z" />',
'              </svg></div>',
'            <div class="nebula-label">Vibe Coding</div>',
'          </div>',
'        </div>',
'',
'        <!-- 3: UI/UX Engineering -->',
'        <div class="nebula-node-wrap theme-dev" data-pct="90" data-x="50" data-y="45">',
'          <div class="nebula-node">',
'            <div class="nebula-cloud"></div>',
'            <div class="nebula-ring"></div>',
'            <div class="nebula-core"><svg viewBox="0 0 24 24">',
'                <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6-1.6 1.6a1 1 0 0 0 1.4 1.4l2.3-2.3a1 1 0 0 0 0-1.4l-2.3-2.3a1 1 0 0 0-1.4 0z" />',
'                <path d="M9.3 17.7a1 1 0 0 0 0-1.4l-1.6-1.6 1.6-1.6a1 1 0 0 0-1.4-1.4l-2.3 2.3a1 1 0 0 0 0 1.4l2.3 2.3a1 1 0 0 0 1.4 0z" />',
'                <rect x="3" y="3" width="18" height="18" rx="2" />',
'              </svg></div>',
'            <div class="nebula-label">UI/UX Engineering</div>',
'          </div>',
'        </div>',
'',
'        <!-- 4: Graphic Design -->',
'        <div class="nebula-node-wrap theme-dev" data-pct="93" data-x="25" data-y="75">',
'          <div class="nebula-node">',
'            <div class="nebula-cloud"></div>',
'            <div class="nebula-ring"></div>',
'            <div class="nebula-core"><svg viewBox="0 0 24 24">',
'                <path d="M12 19l7-7 3 3-7 7-3-3z" />',
'                <path d="M18 13l-1.5-7.5L2 2l3.5 14.5L13 18l5-5z" />',
'              </svg></div>',
'            <div class="nebula-label">Graphic Design</div>',
'          </div>',
'        </div>',
'',
'        <!-- 5: Visual Coding -->',
'        <div class="nebula-node-wrap theme-dev" data-pct="88" data-x="80" data-y="75">',
'          <div class="nebula-node">',
'            <div class="nebula-cloud"></div>',
'            <div class="nebula-ring"></div>',
'            <div class="nebula-core"><svg viewBox="0 0 24 24">',
'                <circle cx="12" cy="12" r="3" />',
'                <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41" />',
'              </svg></div>',
'            <div class="nebula-label">Visual Coding</div>',
'          </div>',
'        </div>',
'',
'        <!-- 6: Product Design -->',
'        <div class="nebula-node-wrap theme-dev" data-pct="85" data-x="45" data-y="18">',
'          <div class="nebula-node">',
'            <div class="nebula-cloud"></div>',
'            <div class="nebula-ring"></div>',
'            <div class="nebula-core"><svg viewBox="0 0 24 24">',
'                <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />',
'                <polyline points="3.27 6.96 12 12.01 20.73 6.96" />',
'                <line x1="12" y1="22.08" x2="12" y2="12" />',
'              </svg></div>',
'            <div class="nebula-label">Product Design</div>',
'          </div>',
'        </div>',
'',
'        <!-- 8: Frontend Dev -->',
'        <div class="nebula-node-wrap theme-dev" data-pct="92" data-x="10" data-y="50">',
'          <div class="nebula-node">',
'            <div class="nebula-cloud"></div>',
'            <div class="nebula-ring"></div>',
'            <div class="nebula-core"><svg viewBox="0 0 24 24">',
'                <rect x="2" y="3" width="20" height="14" rx="2" ry="2" />',
'                <line x1="8" y1="21" x2="16" y2="21" />',
'                <line x1="12" y1="17" x2="12" y2="21" />',
'              </svg></div>',
'            <div class="nebula-label">Frontend Development</div>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <script>',
'        (function () {',
'          const universe = document.getElementById("skills-universe");',
'          if (!universe) return;',
'',
'          const nodes = universe.querySelectorAll(".nebula-node-wrap");',
'          const data = [];',
'          const MIN_DIST = 260;',
'          const FRICTION = 0.95;',
'',
'          let dragOffset = { x: 0, y: 0 };',
'',
'          nodes.forEach((node) => {',
'            const d = {',
'              el: node,',
'              baseX: 15 + Math.random() * 70,',
'              baseY: 15 + Math.random() * 65,',
'              x: Math.random() * 800,',
'              y: Math.random() * 400,',
'              vx: (Math.random() - 0.5) * 8,',
'              vy: (Math.random() - 0.5) * 8,',
'              phaseX: Math.random() * Math.PI * 2,',
'              phaseY: Math.random() * Math.PI * 2,',
'              speedX: 0.01 + Math.random() * 0.01,',
'              speedY: 0.01 + Math.random() * 0.01,',
'              amplitude: 30 + Math.random() * 30,',
'              depth: 0.5 + Math.random() * 1.5,',
'              isDragging: false',
'            };',
'',
'            node.addEventListener("pointerdown", (e) => {',
'              e.preventDefault();',
'              d.isDragging = true;',
'              node.setPointerCapture(e.pointerId);',
'              const rect = universe.getBoundingClientRect();',
'              dragOffset.x = d.x - (e.clientX - rect.left);',
'              dragOffset.y = d.y - (e.clientY - rect.top);',
'            });',
'',
'            node.addEventListener("pointermove", (e) => {',
'              if (d.isDragging) {',
'                const rect = universe.getBoundingClientRect();',
'                const targetX = (e.clientX - rect.left) + dragOffset.x;',
'                const targetY = (e.clientY - rect.top) + dragOffset.y;',
'                d.vx = (targetX - d.x) * 0.8;',
'                d.vy = (targetY - d.y) * 0.8;',
'                d.x = targetX;',
'                d.y = targetY;',
'              }',
'            });',
'',
'            const onRelease = () => {',
'              if (d.isDragging) {',
'                d.isDragging = false;',
'                const rect = universe.getBoundingClientRect();',
'                d.baseX = (d.x / rect.width) * 100;',
'                d.baseY = (d.y / rect.height) * 100;',
'              }',
'            };',
'            node.addEventListener("pointerup", onRelease);',
'            node.addEventListener("pointercancel", onRelease);',
'',
'            data.push(d);',
'          });',
'',
'          let mouseX = 0, mouseY = 0, targetMouseX = 0, targetMouseY = 0;',
'',
'          universe.addEventListener("mousemove", (e) => {',
'            const rect = universe.getBoundingClientRect();',
'            targetMouseX = ((e.clientX - rect.left) / rect.width) - 0.5;',
'            targetMouseY = ((e.clientY - rect.top) / rect.height) - 0.5;',
'          });',
'',
'          universe.addEventListener("mouseleave", () => {',
'            targetMouseX = 0; targetMouseY = 0;',
'          });',
'',
'          function resolveCollisions() {',
'            for (let i = 0; i < data.length; i++) {',
'              for (let j = i + 1; j < data.length; j++) {',
'                const a = data[i], b = data[j];',
'                const dx = b.x - a.x, dy = b.y - a.y;',
'                const distance = Math.hypot(dx, dy);',
'                if (distance < MIN_DIST && distance > 0) {',
'                  const overlap = MIN_DIST - distance;',
'                  const nx = dx / distance, ny = dy / distance;',
'                  const relaxation = overlap * 0.08;',
'                  const rx = nx * relaxation, ry = ny * relaxation;',
'                  if (!a.isDragging) { a.x -= rx * 0.5; a.y -= ry * 0.5; }',
'                  if (!b.isDragging) { b.x += rx * 0.5; b.y += ry * 0.5; }',
'                  const force = overlap * 0.04;',
'                  if (!a.isDragging) { a.vx -= nx * force; a.vy -= ny * force; }',
'                  if (!b.isDragging) { b.vx += nx * force; b.vy += ny * force; }',
'                  const tx = -ny, ty = nx;',
'                  const relativeVelocityT = (a.vx * tx + a.vy * ty) - (b.vx * tx + b.vy * ty);',
'                  const glide = relativeVelocityT * 0.15;',
'                  if (!a.isDragging) { a.vx -= tx * glide; a.vy -= ty * glide; }',
'                  if (!b.isDragging) { b.vx += tx * glide; b.vy += ty * glide; }',
'                  if (!a.isDragging) { a.vx *= 0.99; a.vy *= 0.99; }',
'                  if (!b.isDragging) { b.vx *= 0.99; b.vy *= 0.99; }',
'                }',
'              }',
'            }',
'          }',
'',
'          function animate() {',
'            mouseX += (targetMouseX - mouseX) * 0.03;',
'            mouseY += (targetMouseY - mouseY) * 0.03;',
'            const rect = universe.getBoundingClientRect();',
'            const w = rect.width, h = rect.height;',
'            data.forEach((d) => {',
'              if (d.isDragging) return;',
'              d.phaseX += d.speedX; d.phaseY += d.speedY;',
'              const ox = Math.sin(d.phaseX) * d.amplitude;',
'              const oy = Math.cos(d.phaseY) * d.amplitude;',
'              const px = mouseX * 60 * d.depth;',
'              const py = mouseY * 60 * d.depth;',
'              const hx = (d.baseX / 100) * w, hy = (d.baseY / 100) * h;',
'              const homeForce = 0.025;',
'              d.vx += (hx + ox + px - d.x) * homeForce;',
'              d.vy += (hy + oy + py - d.y) * homeForce;',
'              const minSpeed = 1.2;',
'              const speed = Math.hypot(d.vx, d.vy);',
'              if (speed < minSpeed) {',
'                d.vx += (Math.random() - 0.5) * 0.2;',
'                d.vy += (Math.random() - 0.5) * 0.2;',
'              }',
'              d.vx *= FRICTION; d.vy *= FRICTION;',
'              d.x += d.vx; d.y += d.vy;',
'              // TEXT-SAFE SOFT BOUNDARY (Asymmetric)',
'              const padX = 140;',
'              const padYTop = 80;',
'              const padYBot = 160;',
'              const ef = 0.08;',
'',
'              if (d.x < padX) d.vx += (padX - d.x) * ef;',
'              if (d.x > w - padX) d.vx -= (d.x - (w - padX)) * ef;',
'              if (d.y < padYTop) d.vy += (padYTop - d.y) * ef;',
'              if (d.y > h - padYBot) d.vy -= (d.y - (h - padYBot)) * ef;',
'',
'              // Final hard-wall safety',
'              const safeX = 100;',
'              const safeYTop = 40;',
'              const safeYBot = 110;',
'              if (d.x < safeX) { d.x = safeX; d.vx *= 0.5; }',
'              if (d.x > w - safeX) { d.x = w - safeX; d.vx *= 0.5; }',
'              if (d.y < safeYTop) { d.y = safeYTop; d.vy *= 0.5; }',
'              if (d.y > h - safeYBot) { d.y = h - safeYBot; d.vy *= 0.5; }',
'            });',
'            resolveCollisions();',
'            data.forEach((d) => { d.el.style.transform = "translate3d(" + d.x + "px, " + d.y + "px, 0)"; });',
'            requestAnimationFrame(animate);',
'          }',
'          animate();',
'        })();',
'      </script>'
)

$final = $content[0..($start-1)] + $newNodesAndScript + $content[($end+1)..($content.Length-1)];
$final | Set-Content $path -Encoding UTF8;
Write-Host "Success";
